services:
  - type: web
    name: school-timetable-api
    env: python
    repo: https://github.com/Harati-Ahmed/school-timetable
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: ENVIRONMENT
        value: production
      - key: API_HOST
        value: 0.0.0.0
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_PROJECT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: OAUTH_REDIRECT_URI
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false 